package:
    name: "predictmd-texlive"
    version: "2017-20170524"

requirements:
    build:
        - cairo
        - git
        - pkg-config
        - poppler
        - poppler-data
    run:
        - cairo
        - git
        - pkg-config
        - poppler
        - poppler-data
